### ISSUE TITLE
RegistrationError, Failed to get power state for node  Error: IPMI call failed: power status.

### ISSUE THREAD

**Issue by rakeshk121** [metal3-io/metal3-dev-env#1298]
I am setting up the metal3 in Ubuntu 20 , 

The env variables used are :-

```
export CAPM3_VERSION=v1beta1
export CAPI_VERSION=v1beta1
export IMAGE_OS=ubuntu
export NUM_NODES=4
export BMC_DRIVER=ipmi
export CONTAINER_RUNTIME=docker
export EPHEMERAL_CLUSTER=kind
```

I have run the `make` command , post the setup of metal3, it is showing the below output :-

```
./04_verify.sh
Logging to ./logs/04_verify-2023-09-12-151022.log
OK - Network provisioning exists
OK - Network external exists
OK - Kubernetes cluster reachable

OK - Fetch CRDs
OK - CRD clusters.cluster.x-k8s.io created
OK - CRD kubeadmconfigs.bootstrap.cluster.x-k8s.io created
OK - CRD kubeadmconfigtemplates.bootstrap.cluster.x-k8s.io created
OK - CRD machinedeployments.cluster.x-k8s.io created
OK - CRD machines.cluster.x-k8s.io created
OK - CRD machinesets.cluster.x-k8s.io created
OK - CRD baremetalhosts.metal3.io created

OK - deployments capm3-system:capm3-controller-manager created
OK - capm3-system:capm3-controller-manager deployments replicas correct
OK - deployments capi-system:capi-controller-manager created
OK - capi-system:capi-controller-manager deployments replicas correct
OK - deployments capi-kubeadm-bootstrap-system:capi-kubeadm-bootstrap-controller-manager created
OK - capi-kubeadm-bootstrap-system:capi-kubeadm-bootstrap-controller-manager deployments replicas correct
OK - deployments capi-kubeadm-control-plane-system:capi-kubeadm-control-plane-controller-manager created
OK - capi-kubeadm-control-plane-system:capi-kubeadm-control-plane-controller-manager deployments replicas correct
OK - deployments baremetal-operator-system:baremetal-operator-controller-manager created
OK - baremetal-operator-system:baremetal-operator-controller-manager deployments replicas correct
OK - Replica sets with label cluster.x-k8s.io/provider=infrastructure-metal3 created
OK - infrastructure-metal3 replicas correct for replica set 0
OK - infrastructure-metal3 replicas correct for replica set 1
OK - Replica sets with label cluster.x-k8s.io/provider=cluster-api created
OK - cluster-api replicas correct for replica set 0
OK - Replica sets with label cluster.x-k8s.io/provider=bootstrap-kubeadm created
OK - bootstrap-kubeadm replicas correct for replica set 0
OK - Replica sets with label cluster.x-k8s.io/provider=control-plane-kubeadm created
OK - control-plane-kubeadm replicas correct for replica set 0
OK - Fetch Baremetalhosts
OK - Fetch Baremetalhosts VMs

   - Waiting for task completion (up to 2400 seconds)  - Command: 'check_bm_hosts node-0 ipmi://192.168.111.1:6230 admin password 00:b5:60:ad:b5:d1'
```

When i describe the baremetal hosts, I see this 
```
 Error Message:  Failed to get power state for node 333c7186-5129-4079-9145-853a59323972. Error: IPMI call failed: power status.
 Error Type:     registration error
```

The below are some additional information:

<img width="1404" alt="image" src="https://github.com/metal3-io/metal3-dev-env/assets/22984193/259b7cb5-eb9c-4a9a-802a-aba4a4c0b31c">

**Comment by rakeshk121** [comment]
I have also tried with redfish as BMC_DRIVER , could not get a sucesfull installation with that as well

After running the  make  command , at the end it is stuck with the following message:

```
- Waiting for task completion (up to 2400 seconds)  - Command: 'check_bm_hosts node-0 redfish+http://192.168.111.1:8000/redfish/v1/Systems/6be5c1d8-935f-48c3-a3a0-83482d408675 admin password 00:3a:e4:33:47:3c'
```
When I describe the baremetalhost node-0, i see the below error

```
Normal  RegistrationError  7m25s  metal3-baremetal-controller  Failed to get power state for node e84715bb-2fae-43d4-8241-94916138fba2. Error: HTTP GET http://192.168.111.1:8000/redfish/v1/Systems/6be5c1d8-935f-48c3-a3a0-83482d408675 returned code 500. Base.1.0.GeneralError: Error when connecting to the libvirt URI "qemu+ssh://root@192.168.111.1/system?&keyfile=/root/ssh/id_rsa_virt_power&no_verify=1&no_tty=1": Cannot recv data: root@192.168.111.1: Permission denied (publickey).: Connection reset by peer Extended information: [{'@odata.type': '/redfish/v1/$metadata#Message.1.0.0.Message', 'MessageId': 'Base.1.0.GeneralError'}]

Error Message:  Failed to get power state for node e84715bb-2fae-43d4-8241-94916138fba2. Error: HTTP GET http://192.168.111.1:8000/redfish/v1/Systems/6be5c1d8-935f-48c3-a3a0-83482d408675 returned code 500. Base.1.0.GeneralError: Error when connecting to the libvirt URI "qemu+ssh://root@192.168.111.1/system?&keyfile=/root/ssh/id_rsa_virt_power&no_verify=1&no_tty=1": Cannot recv data: root@192.168.111.1: Permission denied (publickey).: Connection reset by peer Extended information: [{'@odata.type': '/redfish/v1/$metadata#Message.1.0.0.Message', 'MessageId': 'Base.1.0.GeneralError'}]

```

**Comment by dtantsur** [comment]
@rakeshk121 the BMC emulator reports that it cannot access the virtual host (the machine where the VMs are running). There may be many reasons for that. If you look for a `vbmc` (IPMI) or `sushy-tools` (Redfish) containers and log into each of them, you can try SSH'ing into the virtual host with the provided IP and key file and checking why it fails.

/triage needs-information

**Comment by rakeshk121** [comment]
@dtantsur thanks for the suggestion

These are the logs of `vbmc` container

```
core@nodea14:~$ docker logs -f a19488a16e26
libvirt: XML-RPC error : Cannot recv data: Warning: Permanently added '192.168.111.1' (ED25519) to the list of known hosts.
root@192.168.111.1: Permission denied (publickey).: Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/virtualbmc/utils.py", line 47, in __enter__
    self.conn = libvirt.openReadOnly(self.uri)
  File "/usr/lib64/python3.9/site-packages/libvirt.py", line 349, in openReadOnly
    raise libvirtError('virConnectOpenReadOnly() failed')
libvirt.libvirtError: Cannot recv data: Warning: Permanently added '192.168.111.1' (ED25519) to the list of known hosts.
root@192.168.111.1: Permission denied (publickey).: Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pyghmi/ipmi/bmc.py", line 175, in handle_raw_request
    return self.get_chassis_status(session)
  File "/usr/lib/python3.9/site-packages/pyghmi/ipmi/bmc.py", line 91, in get_chassis_status
    powerstate = self.get_power_state()
  File "/usr/lib/python3.9/site-packages/virtualbmc/vbmc.py", line 129, in get_power_state
    with utils.libvirt_open(readonly=True, **self._conn_args) as conn:
  File "/usr/lib/python3.9/site-packages/virtualbmc/utils.py", line 54, in __enter__
    raise exception.LibvirtConnectionOpenError(uri=self.uri, error=e)
virtualbmc.exception.LibvirtConnectionOpenError: Fail to establish a connection with libvirt URI "qemu+ssh://root@192.168.111.1/system?&keyfile=/root/ssh/id_rsa_virt_power&no_verify=1&no_tty=1". Error: Cannot recv data: Warning: Permanently added '192.168.111.1' (ED25519) to the list of known hosts.
root@192.168.111.1: Permission denied (publickey).: Connection reset by peer
libvirt: XML-RPC error : Cannot recv data: root@192.168.111.1: Permission denied (publickey).: Connection reset by peer
```

I have exec into the vbmc container and tried to ssh into the virtual host , Got permission denied for the ssh
```
[root@nodea14 /]# ssh -v -i /root/ssh/id_rsa_virt_power  root@192.168.111.1
OpenSSH_8.7p1, OpenSSL 3.0.7 1 Nov 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: configuration requests final Match pass
debug1: re-parsing configuration
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug1: Connecting to 192.168.111.1 [192.168.111.1] port 22.
debug1: Connection established.
debug1: identity file /root/ssh/id_rsa_virt_power type 0
debug1: identity file /root/ssh/id_rsa_virt_power-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.9
debug1: compat_banner: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.9 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.111.1:22 as 'root'
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:yOoKWNnaN1jPxj+BRFRNyOr+aAHj++yLLxZjP39A3D4
debug1: load_hostkeys: fopen /root/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '192.168.111.1' is known and matches the ED25519 host key.
debug1: Found key in /root/.ssh/known_hosts:1
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /root/ssh/id_rsa_virt_power RSA SHA256:Ot5mJxupY0a//xkfk457i7ggM2kDR+aGCiDbN43Xrm0 explicit
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /root/ssh/id_rsa_virt_power RSA SHA256:Ot5mJxupY0a//xkfk457i7ggM2kDR+aGCiDbN43Xrm0 explicit
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
root@192.168.111.1: Permission denied (publickey).
```

**Comment by adilGhaffarDev** [comment]
cc @adilGhaffarDev

**Comment by Rozzii** [comment]
If you are planning to work on this @adilGhaffarDev  please remove the stale label
