### ISSUE TITLE
Control-plane creation error when using CentOS 8 as IMAGE_NAME_CENTOS

### ISSUE THREAD

**Issue by alosadagrande** [metal3-io/metal3-dev-env#263]
I have been testing the official cloud CentOS 8 image as IMAGE_NAME_CENTOS 
 in metal3-dev-env without success. 

Some issues/ facts:

- I am using cloud image [CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2](https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2)
- CentOS 8 ships cloud-init 18.5, so it is the same version as the centos-update.qcow2 that works perfectly OK.
- Found some issues when moving from CentOS7 to 8 with docker dependencies. They were addressed by adding --nobest option to yum (worth researching cri-o or containerd support in kubeadm. Probably once we get this fixed with docker):

```yaml    
    preKubeadmCommands:
      - ifup eth1
      - yum update -y
      - yum install yum-utils -y
      - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      - setenforce 0
      - sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
      - yum install docker-ce docker-ce-cli --disableexcludes=kubernetes --nobest -y
      - >-
        yum install gcc kernel-headers kernel-devel keepalived
        device-mapper-persistent-data lvm2
        kubelet kubeadm kubectl --disableexcludes=kubernetes -y
      - usermod -aG docker centos
      - systemctl enable --now docker keepalived kubelet
```

Then everytime I run the script provision_controlplane.sh I always stuck at the fact that the /tmp/kubeadm.yaml file is not created in the control-plane VM. So I understand that kubeadm init command cannot be executed and provisioning is not finished.

From the cloud-init logs I can see:

```
2020-03-18 16:31:01,467 - util.py[WARNING]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.6/site-packages/cloudinit/config/cc_write_files.py'>) failed
2020-03-18 16:31:01,467 - util.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.6/site-packages/cloudinit/config/cc_write_files.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cloudinit/util.py", line 1419, in chownbyname
    uid = pwd.getpwnam(user).pw_uid
KeyError: "getpwnam(): name not found: 'centos'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cloudinit/stages.py", line 813, in _run_modules
    freq=freq)
  File "/usr/lib/python3.6/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3.6/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python3.6/site-packages/cloudinit/config/cc_write_files.py", line 82, in handle
    write_files(name, files)
  File "/usr/lib/python3.6/site-packages/cloudinit/config/cc_write_files.py", line 122, in write_files
    util.chownbyname(path, u, g)
  File "/usr/lib/python3.6/site-packages/cloudinit/util.py", line 1423, in chownbyname
    raise OSError("Unknown user or group: %s" % (e))
OSError: Unknown user or group: "getpwnam(): name not found: 'centos'"
...
...
...
Complete!
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
Created symlink /etc/systemd/system/multi-user.target.wants/keepalived.service → /usr/lib/systemd/system/keepalived.service.
Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /usr/lib/systemd/system/kubelet.service.
unable to read config from "/tmp/kubeadm.yaml" : open /tmp/kubeadm.yaml: no such file or directory
To see the stack trace of this error execute with --v=5 or higher
cp: cannot stat '/etc/kubernetes/admin.conf': No such file or directory
chown: cannot access '/home/centos/.kube/config': No such file or directory
Cloud-init v. 18.5 running 'modules:final' at Wed, 18 Mar 2020 16:31:03 +0000. Up 11.11 seconds.
2020-03-18 16:34:36,605 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
2020-03-18 16:31:03,463 - util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/runcmd'] with allowed return codes [0] (shell=False, capture=False)
2020-03-18 16:34:36,605 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
2020-03-18 16:34:36,606 - util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cloudinit/util.py", line 876, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3.6/site-packages/cloudinit/util.py", line 2068, in subp
    cmd=args)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/runcmd']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2020-03-18 16:34:36,608 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)

2020-03-18 16:34:36,609 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2020-03-18 16:34:36,609 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.6/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
2020-03-18 16:34:36,609 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.6/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cloudinit/stages.py", line 813, in _run_modules
    freq=freq)
  File "/usr/lib/python3.6/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3.6/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python3.6/site-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python3.6/site-packages/cloudinit/util.py", line 883, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands

2020-03-18 16:34:36,608 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2020-03-18 16:34:36,609 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.6/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 18.5 finished at Wed, 18 Mar 2020 16:34:36 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/sda2].  Up 224.45 seconds
```

* Any ideas, why the kubeadm.yaml file is not copied? 
* Who is responsible for copying it?

Since the centos-update.qcow2 which is located in the nordix CI runs successfully I tried with CentOS7 cloud image + cloud-init 18.5. However, the result is similar to the CentOS 8 image: missing file /tmp/kubeadm.yaml. 

* So I am wondering what changes were applied to the centos-update image? Anyone has that info documented?

**Comment by maelk** [comment]
This is what was done on the Centos-updated.qcow2 image : 
```
sudo yum update -y cloud-init
sudo yum clean all
sudo rm -rf /var/cache/yum/*
```

**Comment by maelk** [comment]
It looks like it is trying to write a file with the "centos" user as owner, but the "centos" user does not exist. Can you show the content of the "files" section ?

**Comment by alosadagrande** [comment]
Sure:

```yaml
    files:
      - path: /etc/keepalived/keepalived.conf
        content: |
          ! Configuration File for keepalived
          global_defs {
              notification_email {
              sysadmin@example.com
              support@example.com
              }
              notification_email_from lb@example.com
              smtp_server localhost
              smtp_connect_timeout 30
          }
          vrrp_instance VI_1 {
              state MASTER
              interface eth1
              virtual_router_id 1
              priority 101
              advert_int 1
              virtual_ipaddress {
                  {{ CLUSTER_APIENDPOINT_HOST }}
              }
          }
      - path: /etc/sysconfig/network-scripts/ifcfg-eth1
        owner: root:root
        permissions: '0644'
        content: |
          BOOTPROTO=dhcp
          DEVICE=eth1
          ONBOOT=yes
          TYPE=Ethernet
          USERCTL=no
      - path: /etc/yum.repos.d/kubernetes.repo
        owner: root:root
        permissions: '0644'
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=0
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      - path: /home/centos/.ssh/authorized_keys
        owner: centos:centos
        permissions: '0600'
        content: {{ SSH_PUB_KEY_CONTENT }}
```

**Comment by maelk** [comment]
The issue might be the ssh key here, it does not get created properly because the user or group "centos" does not exist

**Comment by maelk** [comment]
The actual problem is that the files are written before the users are created in cloud-init. So the SSH key file will fail to be created. All following files will not be created either. Then cloud-init creates the user and tries to run Kubeadm, this fails because Kubeadmconfig.yaml is absent, since it was not created due to the failure on the ssh key. The solution is to create the ssh key with ownership set to "root:root" and then add a preKubeadmCommand to set the proper ownership (in. the /home/centos!)

**Comment by alosadagrande** [comment]
Agree. Thanks for the explanation. I already changed the KubeadmControlPlane with your suggestions and the target cluster control-plane boot up successfully.

I'll prepare a PR and close the issue when done.

Thanks @maelk and @fmuyassarov

**Comment by alosadagrande** [comment]
PR #264 solved the issue
