### ISSUE TITLE
metal3-dev-env 'make' fails

### ISSUE THREAD

**Issue by Jaakko-Os** [metal3-io/metal3-dev-env#449]
Environment deployment occasionally fails to:

```
NAMESPACE   NAME     STATUS   PROVISIONING STATUS   CONSUMER   BMC                                                                                         HARDWARE PROFILE   ONLINE   ERROR
metal3      node-0   OK       ready                            ipmi://192.168.111.1:6230                                                                   unknown            false
metal3      node-1   OK       ready                            redfish+http://192.168.111.1:8000/redfish/v1/Systems/fd70002e-1b78-444c-82b7-cf31e18a99d0   unknown            false
metal3      node-2   OK       ready                            ipmi://192.168.111.1:6232                                                                   unknown            false
metal3      node-3   error    registration error               redfish+http://192.168.111.1:8000/redfish/v1/Systems/4bf705f5-a542-487b-9c50-475f8dbea88c                      false    Failed to get power
state for node 1709a1f9-d2bb-44cf-a28e-f314245e7f8b. Error: HTTP GET http://192.168.111.1:8000/redfish/v1/Systems/4bf705f5-a542-487b-9c50-475f8dbea88c returned code 500. Base.1.0.GeneralError: [Errno 17]
 File exists: '/tmp/sushy-emulator'
```

Seen also in CI job failures https://jenkins.nordix.org/view/Airship/job/airship_master_feature_tests_upgrade_ubuntu/30/console

**Comment by fmuyassarov** [comment]
@Jaakko-Os 
Can you please share the logs of BMO, CAPM3, and Ironic container?

**Comment by Jaakko-Os** [comment]
Here are all the available logs:
[logs-jenkins-airship_master_feature_tests_upgrade_ubuntu-30.zip](https://github.com/metal3-io/metal3-dev-env/files/5192732/logs-jenkins-airship_master_feature_tests_upgrade_ubuntu-30.zip)

**Comment by fmuyassarov** [comment]
@Jaakko-Os are you able to reproduce it?

**Comment by Jaakko-Os** [comment]
> @Jaakko-Os are you able to reproduce it?

randomly, so it's difficult to verify fix candidates

**Comment by maelk** [comment]
that looks like a bug in sushy-tools. it is returning 500 apparently

**Comment by Jaakko-Os** [comment]
now seeing the same problem when running local tests in my city cloud VM:

```
metal3      node-1   error    registration error               redfish+http://192.168.111.1:8000/redfish/v1/Systems/6a5dcc2d-22d3-47b8-a419-471917801f39                      false    Failed to get power
state for node 8dad1309-43c8-4c80-9987-33399310cef1. Error: HTTP GET http://192.168.111.1:8000/redfish/v1/Systems/6a5dcc2d-22d3-47b8-a419-471917801f39 returned code 500. Base.1.0.GeneralError: [Errno 17]
 File exists: '/tmp/sushy-emulator'
```

**Comment by maelk** [comment]
Here are the sushy-tools logs showing the error:

```
* Running on http://[::]:8000/ (Press CTRL+C to quit)
::ffff:192.168.111.1 - - [08/Sep/2020 02:52:18] "[37mGET /redfish/v1/ HTTP/1.1[0m" 200 -
::ffff:192.168.111.1 - - [08/Sep/2020 02:52:18] "[37mGET /redfish/v1/ HTTP/1.1[0m" 200 -
[2020-09-08 02:52:19,047] ERROR in main: Unexpected FileExistsError: [Errno 17] File exists: '/tmp/sushy-emulator'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/main.py", line 197, in decorator
    return decorated_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/main.py", line 205, in decorator
    response = decorated_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/main.py", line 566, in system_resource
    with Resources() as resources:
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/main.py", line 110, in __new__
    cls.INDICATORS = inddriver.StaticDriver.initialize(
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/resources/indicators/staticdriver.py", line 35, in initialize
    cls._indicators.make_permanent(
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/memoize.py", line 82, in make_permanent
    os.makedirs(dbpath)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/sushy-emulator'
::ffff:192.168.111.1 - - [08/Sep/2020 02:52:19] "[35m[1mGET /redfish/v1/Systems/dadf7bf0-e41e-4005-9db5-29080ab90f72 HTTP/1.1[0m" 500 -
[2020-09-08 02:52:22,322] ERROR in main: Unexpected TypeError: Dict is not yet persistent
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/main.py", line 197, in decorator
    return decorated_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/main.py", line 205, in decorator
    response = decorated_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/main.py", line 584, in system_resource
    indicator_led=resources.indicators.get_indicator_state(
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/resources/indicators/staticdriver.py", line 67, in get_indicator_state
    if identity not in self._indicators:
  File "/usr/local/lib/python3.8/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/memoize.py", line 120, in __getitem__
    with self.connection() as cursor:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/sushy_tools/emulator/memoize.py", line 105, in connection
    raise TypeError('Dict is not yet persistent')
TypeError: Dict is not yet persistent
::ffff:192.168.111.1 - - [08/Sep/2020 02:52:22] "[35m[1mGET /redfish/v1/Systems/bba34b5d-4605-49a2-9131-b295826890f1 HTTP/1.1[0m" 500 -
```

**Comment by maelk** [comment]
That might need to be addressed directly with the people maintaining sushy-tools ?

**Comment by zaneb** [comment]
Sounds to me like a race condition in sushy-tools. This is being tracked [in storyboard](https://storyboard.openstack.org/#!/story/2008166), so I think we can close this.
/close
