### ISSUE TITLE
Operations on node lifecycle not proceeding due to ironic-inspector failure.

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/metal3-dev-env#521]
When creating the metal3-dev-env, the provisioning of a worker and CP node succeeds. However, operations that are performed afterwards are not succeeding as expected.

Operations not proceeding as expected:
- scale-in worker and CP nodes (deleting Ironic pod can be used as a work around)
- scale-up worker and CP nodes
- upgrading of worker and CP nodes

**Note:This problem happens both before and after pivoting.**

So when we trigger anything in kcp or machinedeployment after that we get the following error from BMO:
```
{"level":"info","ts":1602746701.6156812,"logger":"baremetalhost_ironic","msg":"verifying ironic provisioner dependencies","host":"node-0"}
{"level":"info","ts":1602746705.5461686,"logger":"baremetalhost_ironic","msg":"verifying ironic provisioner dependencies","host":"node-2"}
{"level":"info","ts":1602746706.63049,"logger":"baremetalhost_ironic","msg":"verifying ironic provisioner dependencies","host":"node-3"}
{"level":"info","ts":1602746711.6833634,"logger":"baremetalhost_ironic","msg":"error caught while checking endpoint","endpoint":"https://172.22.0.2:5050/v1/","error":"Get \"https://172.22.0.2:5050/v1\": net/http: TLS handshake timeout"}
```

After getting the above error, cleaning has failed. 

```
{"level":"info","ts":1602746981.9928083,"logger":"baremetalhost_ironic","msg":"provisioning image to host","host":"node-0","state":"clean failed"}
{"level":"info","ts":1602746981.9928346,"logger":"baremetalhost_ironic","msg":"checking image settings","host":"node-0","source":"http://172.22.0.1/images/UBUNTU_NODE_IMAGE_K8S_v1.18.8-raw.img","image_os_hash_algo":"md5","image_os_has_value":"http://172.22.0.1/images/UBUNTU_NODE_IMAGE_K8S_v1.18.8-raw.img.md5sum","same":true,"provisionState":"clean failed"}
{"level":"info","ts":1602746981.9928625,"logger":"baremetalhost_ironic","msg":"waiting for host to become available","host":"node-0","state":"clean failed","deploy step":{}}
{"level":"info","ts":1602746981.9928977,"logger":"controllers.BareMetalHost","msg":"saving host status","baremetalhost":"metal3/node-0","provisioningState":"provisioning","operational status":"OK","provisioning

```
Later we check the ironic inspector and it had errors:
```

11:18
2020-10-15 07:07:52.618 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225ESC[00m
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 461, in fire_timers
    timer()
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 151, in _timeout
    current.throw(exc)
  File "/usr/lib/python3.6/site-packages/eventlet/greenthread.py", line 221, in main
    result = function(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 818, in process_request
    proto.__init__(conn_state, self)
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 357, in __init__
    self.handle()
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 390, in handle
    self.handle_one_request()
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 419, in handle_one_request
    self.raw_requestline = self._read_request_line()
  File "/usr/lib/python3.6/site-packages/eventlet/wsgi.py", line 402, in _read_request_line
    return self.rfile.readline(self.server.url_length_limit)
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 241, in recv_into
    return self._base_recv(nbytes, flags, into=True, buffer_=buffer)
  File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 256, in _base_recv
    read = self.read(nbytes, buffer_)
  File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 176, in read
    super(GreenSSLSocket, self).read, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/eventlet/green/ssl.py", line 156, in _call_trampolining
    timeout_exc=timeout_exc('timed out'))
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/__init__.py", line 159, in trampoline
    return hub.switch()
  File "/usr/lib/python3.6/site-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
ssl.SSLError: ('timed out',)
2020-10-15 07:08:25.157 1 DEBUG eventlet.wsgi.server [-] (1) accepted ('::ffff:192.168.26.11', 51326, 0, 0) server /usr/lib/python3.6/site-packages/eventlet/wsgi.py:985ESC[00m
```

**Comment by ismacasti** [comment]
Hi,

I'm seeing similar problem, but for me it's even worse as it makes BMO stop processing.
Ironic Inspector stops processing API calls, but leaves the TCP connections open. This makes BMO stops on its tracks completely until the TCP connections time out on Ironic Inspector side.

```
020-10-29 12:49:24.029 1 DEBUG eventlet.wsgi.server [-] (1) accepted ('::ffff:192.168.155.143', 40352, 0, 0) server /usr/lib/python3.6/site-packages/eventlet/wsgi.py:985
2020-10-29 12:49:39.262 1 INFO eventlet.wsgi.server [req-95c02421-52eb-4c2e-88ba-4ef6d8a49af8 - - - - -] ::ffff:172.22.0.2 "GET /v1/introspection/a7d8df44-4b45-4073-96db-1ccd2752d56a HTTP/1.1" status: 200  len: 536 time: 0.1059532
2020-10-29 12:49:48.259 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:49:48.274 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:49:48.275 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:50:00.246 1 INFO eventlet.wsgi.server [req-6eb26053-7b2d-4519-80d7-761d05f1a907 - - - - -] ::ffff:172.22.0.2 "GET /v1/introspection/1468024d-170a-46c4-9c6d-ca7e5c8dbadb HTTP/1.1" status: 200  len: 536 time: 0.0948458
2020-10-29 12:50:48.263 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:50:48.276 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:50:48.278 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:51:48.269 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:51:48.299 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:51:48.300 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:52:48.274 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:52:48.301 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:52:48.302 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:53:48.279 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:53:48.303 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:53:48.304 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:54:48.292 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:54:48.326 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:54:48.328 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:55:48.310 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:55:48.328 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:55:48.329 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:56:48.314 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:56:48.329 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:56:48.333 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:57:48.319 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:57:48.333 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:57:48.334 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:58:48.323 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:58:48.337 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:58:48.339 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 12:59:48.328 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:59:48.343 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 12:59:48.346 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 13:00:48.334 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 13:00:48.354 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 13:00:48.359 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 13:01:48.338 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 13:01:48.359 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 13:01:48.360 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 13:02:48.343 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.periodic_clean_up' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 13:02:48.360 1 DEBUG futurist.periodics [-] Submitting periodic callback 'ironic_inspector.conductor.manager.sync_with_ironic' _process_scheduled /usr/lib/python3.6/site-packages/futurist/periodics.py:642
2020-10-29 13:02:48.362 1 DEBUG ironic_inspector.conductor.manager [-] Syncing with ironic sync_with_ironic /usr/lib/python3.6/site-packages/ironic_inspector/conductor/manager.py:225
2020-10-29 13:03:14.423 1 DEBUG eventlet.wsgi.server [req-e19b23e5-952b-48bc-8e91-a9e53b6a47a6 - - - - -] (1) timed out ('::ffff:192.168.155.143', 56976, 0, 0) process_request /usr/lib/python3.6/site-packages/eventlet/wsgi.py:823
2020-10-29 13:03:14.428 1 DEBUG eventlet.wsgi.server [-] (1) accepted ('::ffff:192.168.155.143', 40388, 0, 0) server /usr/lib/python3.6/site-packages/eventlet/wsgi.py:985
2020-10-29 13:03:14.569 1 INFO eventlet.wsgi.server [req-8b7726f0-297a-4f2b-bf34-3385a9008d6e - - - - -] ::ffff:192.168.155.143 "GET /v1 HTTP/1.1" status: 200  len: 507 time: 0.1383922
2020-10-29 13:03:15.077 1 DEBUG eventlet.wsgi.server [req-b978bcb9-457c-4d4b-aae3-60e3b5c45a3a - - - - -] (1) timed out ('::ffff:192.168.155.143', 56990, 0, 0) process_request /usr/lib/python3.6/site-packages/eventlet/wsgi.py:823
2020-10-29 13:03:15.079 1 DEBUG eventlet.wsgi.server [-] (1) accepted ('::ffff:192.168.155.143', 40406, 0, 0) server /usr/lib/python3.6/site-packages/eventlet/wsgi.py:985
2020-10-29 13:03:15.184 1 INFO eventlet.wsgi.server [req-44fb9514-e2a5-40d3-bb2f-0de08a3c088d - - - - -] ::ffff:192.168.155.143 "GET /v1 HTTP/1.1" status: 200  len: 507 time: 0.1043842
2020-10-29 13:03:15.292 1 DEBUG eventlet.wsgi.server [req-8a622c99-b1dd-4958-8dba-f73d830d2184 - - - - -] (1) timed out ('::ffff:192.168.155.143', 56994, 0, 0) process_request /usr/lib/python3.6/site-packages/eventlet/wsgi.py:823
2020-10-29 13:03:15.296 1 DEBUG eventlet.wsgi.server [-] (1) accepted ('::ffff:172.22.0.2', 56456, 0, 0) server /usr/lib/python3.6/site-packages/eventlet/wsgi.py:985
2020-10-29 13:03:15.462 1 INFO eventlet.wsgi.server [req-dca6f23b-5124-40f0-b054-8bee5093a1c6 - - - - -] ::ffff:192.168.155.143 "GET /v1 HTTP/1.1" status: 200  len: 507 time: 0.1654518
2020-10-29 13:03:24.979 1 DEBUG eventlet.wsgi.server [req-f3a74acf-600d-482e-a622-74c5829b6816 - - - - -] (1) timed out ('::ffff:192.168.155.143', 39084, 0, 0) process_request /usr/lib/python3.6/site-packages/eventlet/wsgi.py:823
2020-10-29 13:03:24.983 1 DEBUG eventlet.wsgi.server [-] (1) accepted ('::ffff:192.168.155.143', 50796, 0, 0) server /usr/lib/python3.6/site-packages/eventlet/wsgi.py:985
2020-10-29 13:03:24.985 1 DEBUG ironic_inspector.main [-] Returning error to client: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. error_response /usr/lib/python3.6/site-packages/ironic_inspector/main.py:129
2020-10-29 13:03:24.990 1 INFO eventlet.wsgi.server [-] ::ffff:172.22.0.2 "GET /v1/drivers HTTP/1.1" status: 404  len: 387 time: 0.0064244
2020-10-29 13:03:24.991 1 DEBUG eventlet.wsgi.server [-] (1) accepted ('::ffff:192.168.155.143', 50808, 0, 0) server /usr/lib/python3.6/site-packages/eventlet/wsgi.py:985
2020-10-29 13:03:25.082 1 INFO eventlet.wsgi.server [req-2e8fed58-7864-40f0-bfc1-58913e23ebe7 - - - - -] ::ffff:192.168.155.143 "GET /v1 HTTP/1.1" status: 200  len: 507 time: 0.0901825
```

If you check the times, it stopped processing HTTP calls for several minutes until they time out. But I dont' see your SSL error message.

**Comment by szengerle** [comment]
Same problem for an external Ironic/Inspector deployment with openstack-ironic-inspector-8.0.1 on CentOS 8.
Inspector leaves TCP connection open and does not response on HTTP requests. BMO stops working for several minutes. 

Br,
Sebastian

**Comment by szengerle** [comment]
Looks like for some reason BMO does not close TCP sockets to Inspector. 
Since I am neither BMO nor Go expert I workarounded the issue on Inspector side. It does not solve root cause but makes setup mutch more stable:

[DEFAULT]
http_timeout=15
tcp_keepidle=15
client_socket_timeout=15

Br,
Sebastian

**Comment by maelk** [comment]
Hi! This problem (opened sockets on BMO side) should now be fixed. Did you try with the latest code from BMO ?

**Comment by szengerle** [comment]
I am running the image quay.io/metal3-io/baremetal-operator:capm3-v0.4.1.

Br,
Sebastian

**Comment by maelk** [comment]
Could you give it a try with latest ? you should not see the problem anymore with that one

**Comment by szengerle** [comment]
Tested with latest/7c2663e80ca8 and previous Inspector config. All connections are closed by BMO perfectly and no TCP timeout have to be configured at Inspector anylonger. Just for my learning: What was the commit of this bugfix? Thanks.

Br,
Sebastian

**Comment by furkatgofurov7** [comment]
> Tested with latest/7c2663e80ca8 and previous Inspector config. All connections are closed by BMO perfectly and no TCP timeout have to be configured at Inspector anylonger. Just for my learning: What was the commit of this bugfix? Thanks.
> 
> Br,
> Sebastian

@szengerle Hi! This should be the commit you are looking for: https://github.com/metal3-io/baremetal-operator/pull/712/commits/1227ba7bfc6315b650c7a4260776f8b9d6fab39e
