### ISSUE TITLE
sushy-tools image is failing to bring up a container

### ISSUE THREAD

**Issue by digambar15** [metal3-io/metal3-dev-env#593]
I am seeing issue while bringing up container out of sushy-tools image. Container is going in CrashLoopBack.
Anyone knows workaround on this, please share details.

**Comment by digambar15** [comment]
airship@d104:~/vino$ sudo docker run quay.io/metal3-io/sushy-tools
Traceback (most recent call last):
  File "/usr/local/bin/sushy-emulator", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/sushy_tools/emulator/main.py", line 854, in main
    app.config.from_pyfile(args.config)
  File "/usr/local/lib/python3.9/site-packages/flask/config.py", line 131, in from_pyfile
    with open(filename, mode="rb") as config_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/root/sushy/conf.py'

**Comment by fmuyassarov** [comment]
I had dev-env running in a VM, and by just quickly checking the container I see that the conf.py exists in the root/sushy directory


```
ubuntu@fmuyassarov:~$ sudo docker ps
CONTAINER ID   IMAGE                                             COMMAND                  CREATED        STATUS                    PORTS                       NAMES
63046310f1a5   192.168.111.1:5000/localimages/ironic-inspector   "/bin/runlogwatch.sh"    24 hours ago   Up 24 hours (unhealthy)                               ironic-inspector-log-watch
09d32ec5fc77   192.168.111.1:5000/localimages/ironic-inspector   "/bin/runironic-insp…"   24 hours ago   Up 24 hours (healthy)                                 ironic-inspector
0cbae44160bd   192.168.111.1:5000/localimages/ironic             "/bin/runlogwatch.sh"    24 hours ago   Up 24 hours                                           ironic-log-watch
e350c2492fe4   192.168.111.1:5000/localimages/keepalived         "/bin/bash manage-ke…"   24 hours ago   Up 24 hours                                           ironic-endpoint-keepalived
9cbd5132ddb1   192.168.111.1:5000/localimages/ironic             "/bin/runironic-cond…"   24 hours ago   Up 24 hours                                           ironic-conductor
b160a6539621   192.168.111.1:5000/localimages/ironic             "/bin/runironic-api"     24 hours ago   Up 24 hours                                           ironic-api
6e746152dd0a   192.168.111.1:5000/localimages/ironic             "/bin/runmariadb"        24 hours ago   Up 24 hours                                           mariadb
875ea42bbb7d   192.168.111.1:5000/localimages/ironic             "/bin/runhttpd"          24 hours ago   Up 24 hours                                           httpd
2e41a9bacd31   192.168.111.1:5000/localimages/ironic             "/bin/rundnsmasq"        24 hours ago   Up 24 hours                                           dnsmasq
1956ab5fbbed   kindest/node:v1.20.0                              "/usr/local/bin/entr…"   24 hours ago   Up 24 hours               127.0.0.1:34565->6443/tcp   kind-control-plane
34d5773ade97   quay.io/metal3-io/sushy-tools                     "/bin/sh -c 'sushy-e…"   24 hours ago   Up 24 hours                                           sushy-tools
66d9bccb68d2   quay.io/metal3-io/vbmc                            "/bin/sh -c '/usr/bi…"   24 hours ago   Up 24 hours                                           vbmc
0ec121d0f71e   quay.io/metal3-io/ironic                          "/bin/runhttpd"          24 hours ago   Up 24 hours                                           httpd-infra
34d77a0690b6   registry:latest                                   "/entrypoint.sh /etc…"   27 hours ago   Up 24 hours               0.0.0.0:5000->5000/tcp      registry

ubuntu@fmuyassarov:~$ sudo docker exec -it sushy-tools bash
root@fmuyassarov:/# ls
bin  boot  dev	etc  home  lib	lib64  media  mnt  opt	proc  root  run  sbin  srv  sys  tmp  usr  var
root@fmuyassarov:/# cat root/sushy/conf.py 
SUSHY_EMULATOR_LIBVIRT_URI = "qemu+ssh://root@192.168.111.1/system?&keyfile=/root/ssh/id_rsa_virt_power&no_verify=1&no_tty=1"
root@fmuyassarov:/# 
```
But I will anyways test it in a fresh dev-env as well!

**Comment by fmuyassarov** [comment]
@digambar15 The issue is you are not mounting `conf.py` to the container. In dev-env we are creating [conf.py ](https://github.com/metal3-io/metal3-dev-env/blob/7ab1eff181df5b9db21ad9eab8e63c04b24c7281/vm-setup/roles/virtbmc/tasks/setup_tasks.yml#L96) to `/opt/metal3-dev-env/virtualbmc/sushy-tools` directory and then [mounting](https://github.com/metal3-io/metal3-dev-env/blob/c0eaf956828e0aee80a596812ac919128c67edd1/02_configure_host.sh#L208) it to the sushy-tool container.

**Comment by fmuyassarov** [comment]
@digambar15 can we close this issue if you think that the issue you are facing ins't a bug?
