### ISSUE TITLE
Failure to get node power state via ipmitool during the deployment 

### ISSUE THREAD

**Issue by mgazz** [metal3-io/metal3-dev-env#896]
Hello,

I am trying to deploy the metal3 environment via `make`, but the process fails during the verification step with output as following:
```
...
OK - Network provisioning exists
OK - Network baremetal exists
OK - Kubernetes cluster reachable

OK - Fetch CRDs
OK - CRD clusters.cluster.x-k8s.io created
OK - CRD kubeadmconfigs.bootstrap.cluster.x-k8s.io created
OK - CRD kubeadmconfigtemplates.bootstrap.cluster.x-k8s.io created
OK - CRD machinedeployments.cluster.x-k8s.io created
OK - CRD machines.cluster.x-k8s.io created
OK - CRD machinesets.cluster.x-k8s.io created
OK - CRD baremetalhosts.metal3.io created

OK - deployments capm3-system:capm3-controller-manager created
OK - capm3-system:capm3-controller-manager deployments replicas correct
OK - deployments capi-system:capi-controller-manager created
OK - capi-system:capi-controller-manager deployments replicas correct
OK - deployments capi-kubeadm-bootstrap-system:capi-kubeadm-bootstrap-controller-manager created
OK - capi-kubeadm-bootstrap-system:capi-kubeadm-bootstrap-controller-manager deployments replicas correct
OK - deployments capi-kubeadm-control-plane-system:capi-kubeadm-control-plane-controller-manager created
OK - capi-kubeadm-control-plane-system:capi-kubeadm-control-plane-controller-manager deployments replicas correct
OK - deployments baremetal-operator-system:baremetal-operator-controller-manager created
OK - baremetal-operator-system:baremetal-operator-controller-manager deployments replicas correct
OK - Replica sets with label cluster.x-k8s.io/provider=infrastructure-metal3 created
OK - infrastructure-metal3 replicas correct for replica set 0
OK - infrastructure-metal3 replicas correct for replica set 1
OK - Replica sets with label cluster.x-k8s.io/provider=cluster-api created
OK - cluster-api replicas correct for replica set 0
OK - Replica sets with label cluster.x-k8s.io/provider=bootstrap-kubeadm created
OK - bootstrap-kubeadm replicas correct for replica set 0
OK - Replica sets with label cluster.x-k8s.io/provider=control-plane-kubeadm created
OK - control-plane-kubeadm replicas correct for replica set 0
OK - Fetch Baremetalhosts
OK - Fetch Baremetalhosts VMs

   - Waiting for task completion (up to 2400 seconds)  - Command: 'check_bm_hosts node-0 ipmi://192.168.111.1:6230 admin password 00:e9:90:c8:ae:f4'
OK - node-0 Baremetalhost exist
OK - node-0 Baremetalhost address correct
OK - node-0 Baremetalhost mac address correct
FAIL - node-0 Baremetalhost status OK
       expected OK, got error
OK - node-0 Baremetalhost credentials secret exist
OK - node-0 Baremetalhost password correct
OK - node-0 Baremetalhost user correct
OK - node-0 Baremetalhost VM exist
OK - node-0 Baremetalhost VM interface provisioning exist
OK - node-0 Baremetalhost VM interface baremetal exist
FAIL - node-0 Baremetalhost introspecting completed
       expected registering to be in ready available

OK - node-1 Baremetalhost exist
OK - node-1 Baremetalhost address correct
OK - node-1 Baremetalhost mac address correct
OK - node-1 Baremetalhost status OK
OK - node-1 Baremetalhost credentials secret exist
OK - node-1 Baremetalhost password correct
OK - node-1 Baremetalhost user correct
OK - node-1 Baremetalhost VM exist
OK - node-1 Baremetalhost VM interface provisioning exist
OK - node-1 Baremetalhost VM interface baremetal exist
OK - node-1 Baremetalhost introspecting completed
```

Inspecting the `baremetalhosts`, `node-0` reports the following error:
```
Status:
  Error Count:    6
  Error Message:  Failed to get power state for node 7193eaf2-c960-4d25-86c1-55663bc5d689. Error: Command '['ipmitool', '-I', 'lanplus', '-H', '192.168.111.1', '-L', 'ADMINISTRATOR', '-p', '6230', '-U', 'admin', '-R', '7', '-N', '5', '-f', '/tmp/tmpwvt5jum0', 'power', 'status']' timed out after 60 seconds
  Error Type:     registration error
```
I attached [bmh.txt](https://github.com/metal3-io/metal3-dev-env/files/7814088/bmh.txt) so you can see the whole output of `kubectl describe bmh -A`

Also, from the `vbmc` container logs I see the following error:
```
2022-01-05 09:11:14,103 1 INFO VirtualBMC [-] Started vBMC instance for domain node_0
2022-01-05 09:11:14,106 1 INFO VirtualBMC [-] Started vBMC instance for domain node_1
2022-01-05 09:11:14,110 2362 ERROR VirtualBMC [-] Shutdown vBMC for domain node_0, cause [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/virtualbmc/manager.py", line 140, in vbmc_runner
    vbmc.listen(timeout=CONF['ipmi']['session_timeout'])
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/bmc.py", line 192, in listen
    ipmisession.Session.wait_for_rsp(timeout)
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/private/session.py", line 1184, in wait_for_rsp
    if _poller(timeout=timeout):
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/private/session.py", line 249, in _poller
    _io_wait(timeout)
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/private/session.py", line 179, in _io_wait
    intsock.sendto(b'\x01', (myself, iosockets[0].getsockname()[1]))
PermissionError: [Errno 1] Operation not permitted
2022-01-05 09:11:14,113 2363 ERROR VirtualBMC [-] Shutdown vBMC for domain node_1, cause [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/virtualbmc/manager.py", line 140, in vbmc_runner
    vbmc.listen(timeout=CONF['ipmi']['session_timeout'])
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/bmc.py", line 192, in listen
    ipmisession.Session.wait_for_rsp(timeout)
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/private/session.py", line 1184, in wait_for_rsp
    if _poller(timeout=timeout):
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/private/session.py", line 249, in _poller
    _io_wait(timeout)
  File "/usr/lib/python3.6/site-packages/pyghmi/ipmi/private/session.py", line 179, in _io_wait
    intsock.sendto(b'\x01', (myself, iosockets[0].getsockname()[1]))
PermissionError: [Errno 1] Operation not permitted
```

**Comment by furkatgofurov7** [comment]
@mgazz hi, thanks for reporting!
Can you please check the console of the hosts and see what they were doing at the time? Did they PXE boot successfully?

@dtantsur do you have any pointers on why vbmc container could fail to start properly? We do need maybe more logs from other containers?

**Comment by mgazz** [comment]
@furkatgofurov7 Hi,  

node-1 is running while the node-0, the machine reporting the issue, is currently shut off.
```
# virsh list --all
 Id   Name     State
-------------------------
 1    node_1   running
 -    node_0   shut off
```
I can only see the console logs from node_1 (I suspect node_0 never started). Interestingly, node_1 reports the following error:

```
modprobe: FATAL: Module ipmi_smb not found in directory /lib/modules/4.18.0-348.2.1.el8_5.x86_64
modprobe: ERROR: could not insert 'ipmi_si': No such device
grep: /proc/detect_utils.cmdline: No such file or directory
Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
```
Always from node-1, I see the following error while trying to modprobe `ipmi_si`
```
2022-01-05 08:51:10.905 599 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): modprobe ipmi_si execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384^[[00m
[   25.714840] ipmi_si: IPMI System Interface driver
[   25.716012] ipmi_si: Unable to find any System Interface(s)
2022-01-05 08:51:10.934 599 DEBUG oslo_concurrency.processutils [-] CMD "modprobe ipmi_si" returned: 1 in 0.029s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423^[[00m
2022-01-05 08:51:10.935 599 DEBUG oslo_concurrency.processutils [-] 'modprobe ipmi_si' failed. Not Retrying. execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:474^[[00m
2022-01-05 08:51:10.936 599 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99^[[00m
2022-01-05 08:51:10.936 599 DEBUG ironic_lib.utils [-] Command stderr is: "modprobe: ERROR: could not insert 'ipmi_si': No such device
" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100^[[00m
2022-01-05 08:51:10.937 599 DEBUG ironic_lib.utils [-] Command failed: Unexpected error while running command.
Command: modprobe ipmi_si
Exit code: 1
Stdout: ''
Stderr: "modprobe: ERROR: could not insert 'ipmi_si': No such device\n" try_execute /usr/lib/python3.6/site-packages/ironic_lib/utils.py:132^[[00m
```

The ipmi modules are available on the machine from which I deployed the metal3 development environment

```
└❯sudo lsmod | grep ipmi
ipmi_ssif              36864  0
ipmi_si                65536  0
ipmi_devintf           20480  0
ipmi_msghandler       106496  3 ipmi_devintf,ipmi_si,ipmi_ssif
```

Looking at the running containers, the `ironic-conductor` reports a similar error from the one reported by the `baremetalhost`.
```
2022-01-05 08:51:03.271 1 ERROR ironic.conductor.verify [req-1ceb227c-1983-40e1-ab70-5af8ed1f420f - - - - -] Failed to get power state for node 7193eaf2-c960-4d25-86c1-55663bc5d689. Error: Command '['ipmitool', '-I', 'lanplus', '-H', '192.168.111.1', '-L', 'ADMINISTRATOR', '-p', '6230', '-U', 'admin', '-R', '7', '-N', '5', '-f', '/tmp/tmp96tf8kmb', 'power', 'status']' timed out after 60 seconds: subprocess.TimeoutExpired: Command '['ipmitool', '-I', 'lanplus', '-H', '192.168.111.1', '-L', 'ADMINISTRATOR', '-p', '6230', '-U', 'admin', '-R', '7', '-N', '5', '-f', '/tmp/tmp96tf8kmb', 'power', 'status']' timed out after 60 seconds

```

I uploaded what seem to be relevant logs [logs.tar.gz](https://github.com/metal3-io/metal3-dev-env/files/7854069/logs.tar.gz)

Please let me know if I can help inspecting other services involved in the boot process.

**Comment by macaptain** [comment]
I expect there's something in your environment that's interfering with UDP.

The errors in the `vbmc` container logs suggest both nodes failed trying to listen for IPMI. In a default metal3-dev-env with two nodes, one node is controlled by Redfish, the other by IPMI. I expect that when Ironic was talking Redfish (HTTP/TCP) to `node_1`'s BMC, all was well. But your `ipmi` command to `node_0`'s BMC timed out because the UDP socket for IPMI wasn't properly set up by `vbmc`.

Are you running conntrack on your host perchance? See https://stackoverflow.com/a/23869102. Or could iptables be interfering with UDP traffic?

You could also tell Ironic to use Redfish for both hosts as a workaround: `BMC_DRIVER=redfish` in your <username>_config.sh file in the metal3-dev-env checkout.

**Comment by mgazz** [comment]
@macaptain  thank you for the suggestions. 

By setting `BMC_DRIVER=redfish` I managed to circumvent the issue.

With `BMC_DRIVER=mixed`, after restoring the iptables and pulling from master(50fa7121a7680ea6965ed3d77219fb6715681ab3), the deployment reached the end successfully.
